name: Deployment

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USR }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p deploy
            cd deploy

            # Check if the directory exists
            if [ -d "IoT-DIRfram" ]; then
              echo "Directory exists, updating repository"
              cd IoT-DIRfram
              git pull origin main
            else
              echo "Directory does not exist, cloning repository"
              git clone https://github.com/COS301-SE-2024/IoT-DIRfram.git
              cd IoT-DIRfram
            fi

            npm install -g pm2
            cd frontend
            server -s build &
            cd ../backend
            pm2 start server.js --name my-app
            pm2 save
            pm2 startup
            echo 'Deployment successful'
