name: Node.js CI

on:
  push:
    branches: [main, dev, feature/profile]
  pull_request:
    branches: [main, dev, feature/profile]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      continue-on-error: true

    - name: Install dependencies
      run: npm install
           npm ci
      continue-on-error: true
      working-directory: frontend

    - name: Build
      run: npm run build --if-present
      working-directory: frontend
      continue-on-error: true

    - name: Test
      run: npm test
      working-directory: frontend
      continue-on-error: true
