name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - feature/profile
  pull_request:
    branches:
      - main
      - dev
      - feature/profile

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      continue-on-error: true

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
      continue-on-error: true

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
      continue-on-error: true

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
      continue-on-error: true

    - name: Install Node.js dependencies
      run: npm install
      working-directory: frontend
      continue-on-error: true

    - name: Lint Python code with flake8
      run: flake8 backend/
      continue-on-error: true

    - name: Lint Node.js code
      run: npm run lint
      working-directory: frontend
      continue-on-error: true

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install
      working-directory: frontend

    - name: Build Frontend
      run: npm run build
      working-directory: frontend

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # - name: Set up Python
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: "3.10"

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # - name: Install Python dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pytest

    # - name: Install Node.js dependencies
    #   run: npm install
    #   working-directory: frontend

    # - name: Test Python code with pytest
    #   run: pytest backend/tests/

    - name: Test Node.js API
      run: |
        cd api
        npm test

    - name: Test React Frontend
      run: npm test
      working-directory: frontend

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # - name: Set up Python
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: "3.10"

    - name: Install Dependencies
      run: |
        npm install
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      working-directory: frontend

    - name: Deploy to DigitalOcean
      run: |
        scp -r ./frontend/build ${{ secrets.USER }}@${{ secrets.SERVER }}:/path/to/frontend
        scp -r ./api ${{ secrets.USER }}@${{ secrets.SERVER }}:/path/to/api
        scp -r ./backend ${{ secrets.USER }}@${{ secrets.SERVER }}:/path/to/backend
        ssh ${{ secrets.USER }}@${{ secrets.SERVER }} 'sudo systemctl restart your-service'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER: ${{ secrets.SERVER }}
        USER: ${{ secrets.USER }}
